name: Go

on:
  workflow_dispatch:

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - name: Run code check
        run: |
          # 执行所有检查
          for check in EOF spelling; do
            ./hack/verify-$check.sh
          done

  parser_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - name: Build parser
        run: |
          cd parser && make

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16'

      - name: Build the project
        run: |
          make build

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: linux_amd64
          path: |
            bin/
          if-no-files-found: error
